export const MOVIE_TYPES = {
    FETCH_TRENDING_MOVIES_START: "home/FETCH_TRENDING_MOVIES_START",
    FETCH_TRENDING_MOVIES_SUCCESS: "home/FETCH_TRENDING_MOVIES_SUCCESS",
    FETCH_TRENDING_MOVIES_FAILED :"home/FETCH_TRENDING_MOVIES_FAILED",
}