export const ALL_MOVIES_TYPES ={
    FETCH_NOW_PLAYING:"movies/FETCH_NOW_PLAYING",
    FETCH_POPULAR:"movies/FETCH_POPULAR",
    FETCH_TOP_RATED: "movies/FETCH_TOP_RATED",
    FETCH_UPCOMING_MOVIES:"movies/FETCH_UPCOMING_MOVIES",
    FETCH_LATEST: "movies/FETCH_LATEST"
}